package br.ufrn.info;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-12T15:46:59.990-02:00
 * Generated source version: 3.1.4
 *
 * @author Leonardo René (leonardo@info.ufrn.br)
 * @since 12/01/2016
 */
@WebServiceClient(name = "WSCurriculo",
        wsdlLocation = "http://servicosweb.cnpq.br/srvcurriculo/WSCurriculo?wsdl",
        targetNamespace = "http://ws.servico.repositorio.cnpq.br/")
public class WSCurriculoService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ws.servico.repositorio.cnpq.br/", "WSCurriculo");
    public final static QName WSCurriculoPort = new QName("http://ws.servico.repositorio.cnpq.br/", "WSCurriculoPort");
    public final static String ENDPOINT;
    static {
        URL url = null;
        ENDPOINT = "http://servicosweb.cnpq.br/srvcurriculo/WSCurriculo";

        try {
            url = new URL(ENDPOINT+"?wsdl");
        } catch (MalformedURLException e) {
            System.err.println(ENDPOINT+"?wsdl");
            e.printStackTrace();
        }
        WSDL_LOCATION = url;


    }


    public WSCurriculoService() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     *
     * @return
     *     returns WSCurriculo
     */
    @WebEndpoint(name = "WSCurriculoPort")
    public WSCurriculo getWSCurriculoPort() {
        WSCurriculo wsCurriculo = super.getPort(WSCurriculoPort, WSCurriculo.class);

        BindingProvider bp = (BindingProvider)wsCurriculo;
        bp.getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, ENDPOINT);

        return wsCurriculo;
    }

}
