package br.ufrn.info;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-12T15:46:59.983-02:00
 * Generated source version: 3.1.4
 *
 * @author Leonardo René (leonardo@info.ufrn.br)
 * @since 12/01/2016.
 */
@WebService(targetNamespace = "http://ws.servico.repositorio.cnpq.br/", name = "WSCurriculo")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WSCurriculo {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://ws.servico.repositorio.cnpq.br/", partName = "return")
    public java.lang.String getDataAtualizacaoCVPorUsuario(
            @WebParam(partName = "id", name = "id")
                    java.lang.String id,
            @WebParam(partName = "login", name = "login")
                    java.lang.String login
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://ws.servico.repositorio.cnpq.br/", partName = "return")
    public java.lang.String getIdentificadorCNPqPorUsuario(
            @WebParam(partName = "cpf", name = "cpf")
                    java.lang.String cpf,
            @WebParam(partName = "nomeCompleto", name = "nomeCompleto")
                    java.lang.String nomeCompleto,
            @WebParam(partName = "dataNascimento", name = "dataNascimento")
                    java.lang.String dataNascimento,
            @WebParam(partName = "login", name = "login")
                    java.lang.String login
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://ws.servico.repositorio.cnpq.br/", partName = "return")
    public byte[] getCurriculoCompactadoPorUsuario(
            @WebParam(partName = "id", name = "id")
                    java.lang.String id,
            @WebParam(partName = "login", name = "login")
                    java.lang.String login
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://ws.servico.repositorio.cnpq.br/", partName = "return")
    public java.lang.String getIdentificadorCNPq(
            @WebParam(partName = "cpf", name = "cpf")
                    java.lang.String cpf,
            @WebParam(partName = "nomeCompleto", name = "nomeCompleto")
                    java.lang.String nomeCompleto,
            @WebParam(partName = "dataNascimento", name = "dataNascimento")
                    java.lang.String dataNascimento
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://ws.servico.repositorio.cnpq.br/", partName = "return")
    public java.lang.String getOcorrenciaCVPorUsuario(
            @WebParam(partName = "id", name = "id")
                    java.lang.String id,
            @WebParam(partName = "login", name = "login")
                    java.lang.String login
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://ws.servico.repositorio.cnpq.br/", partName = "return")
    public byte[] getCurriculoCompactado(
            @WebParam(partName = "id", name = "id")
                    java.lang.String id
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://ws.servico.repositorio.cnpq.br/", partName = "return")
    public java.lang.String getOcorrenciaCV(
            @WebParam(partName = "id", name = "id")
                    java.lang.String id
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://ws.servico.repositorio.cnpq.br/", partName = "return")
    public java.lang.String getDataAtualizacaoCV(
            @WebParam(partName = "id", name = "id")
                    java.lang.String id
    );
}
